baseURL = "http://example.org/"
languageCode = "en-us"
title = "Violin Plus"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "#about"
        weight  = 2
    [[menu.nav]]
        name    = "Learn"
        url     = "#learn"
        weight  = 3
    [[menu.nav]]
        name    = "Pricing"
        url     = "#pricing"
        weight  = 4
    [[menu.nav]]
        name    = "Contact"
        url     = "#contact"
        weight  = 5

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Violin Plus"
    author = "Alla Petrichei"
    # Google Analitycs
    googleAnalitycsID = ""

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "Online Violin, Viola & Music Theory"
        description = "2-3 lines of text about services"
        btn     = true
        btnText = "Book a taster session"
        btnURL  = "#contact"
        [[params.banner.flipText]]
            title   = "Lessons"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "Hello, Iâ€™m a UI/UX Designer & Front End Developer from Victoria, Australia. I hold a master degree of Web Design from the World University.And scrambled it to make a type specimen book. It has survived not only five centuries. <br> <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda iusto reiciendis placeat. Temporibus, vero."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT YOU THINK ?"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText = "Contact with me"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    